"""empty message

Revision ID: 03327207019a
Revises: 3fc349149b78
Create Date: 2019-04-22 01:36:55.049922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03327207019a'
down_revision = '3fc349149b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'user', ['user_id'], ['id'])
    op.drop_column('bookmarks', 'user.id')
    op.add_column('user', sa.Column('img_url', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'img_url')
    op.add_column('bookmarks', sa.Column('user.id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'bookmarks', type_='foreignkey')
    op.create_foreign_key(None, 'bookmarks', 'user', ['user.id'], ['id'])
    # ### end Alembic commands ###
